BuildDirectory      := ../.Build
EFIRoot             := $(BuildDirectory)/EFI
ImgSysMirror        := .Build

BootImg             := $(BuildDirectory)/BootImg.img

CC                  := gcc
CFLAGS := \
-std=c11 \
-ffreestanding \
-fno-stack-protector \
-fno-stack-check \
-fno-lto \
-fno-pie \
-fno-builtin \
-fno-omit-frame-pointer \
-mno-red-zone \
-mno-mmx \
-mno-sse \
-mno-sse2 \
-mno-sse3 \
-mno-ssse3 \
-mno-sse4.1 \
-mno-sse4.2 \
-mno-sse4 \
-mno-avx \
-mno-avx2 \
-mno-80387 \
-m64 \
-march=x86-64 \
-mcmodel=kernel \
-Wall \
-Wextra \
-Werror \
-Wno-unused-parameter \
-Wno-unused-variable \
-O2 \
-g \
-I../KModLibs/Includes

KOFILES             := $(patsubst %.c,$(ImgSysMirror)/%.ko,$(shell find . -name '*.c'))

.PHONY: \
BuildModules \
clean \
BootImg

BuildModules: \
$(KOFILES)\
BootImg

# C
$(ImgSysMirror)/%.ko: %.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@
BootImg: $(KOFILES)
	@mkdir -p $(BuildDirectory)
	@(cd $(ImgSysMirror) && find . | cpio -o -H newc) > $(BootImg)
	@cp $(BootImg) $(EFIRoot)/
clean:
	@rm -rf $(BuildDirectory)/BootImg.img
