#pragma once

#include <AllTypes.h>
#include <DevFS.h>
#include <KHeap.h>
#include <KrnPrintf.h>
#include <String.h>
#include <VFS.h>

typedef struct BlockDisk
{
    const char* Name;        /* "sda", "sdb" */
    void*       CtrlCtx;     /* controller-private context */
    uint64_t    TotalBlocks; /* total logical blocks */
    long        BlockSize;   /* bytes per block (512/4096) */
    BlockDevOps Ops;         /* controller ops (filled by caller) */

} BlockDisk;

typedef struct BlockPart
{
    const char* Name;      /* "sda1", "sda2" */
    BlockDisk*  Parent;    /* parent disk */
    uint64_t    StartLba;  /* starting LBA of the partition */
    uint64_t    NumBlocks; /* length in blocks */
    long        BlockSize; /* inherited from disk */
    BlockDevOps Ops;       /* translated ops (generated by block layer) */

} BlockPart;

int BlockRegisterDisk(BlockDisk* __Disk__);
int BlockRegisterPartition(BlockPart* __Part__);
int BlockRegisterGPTPartitions(BlockDisk*  __Disk__,
                               const void* __GptHeader__,
                               const void* __GptEntries__,
                               long        __EntryCount__);
int BlockRegisterMBRPartitions(BlockDisk* __Disk__, const void* __MbrSector__);

int BlockMakeName(char*       __Out__,
                  long        __Cap__,
                  const char* __Prefix__,
                  long        __Index__); /* e.g., "sd" + index -> "sda" */
int BlockMakePartName(char*       __Out__,
                      long        __Cap__,
                      const char* __DiskName__,
                      long        __PartIndex__); /* "sda" + 1 -> "sda1" */

KEXPORT(BlockRegisterDisk);
KEXPORT(BlockRegisterPartition);
KEXPORT(BlockRegisterGPTPartitions);
KEXPORT(BlockRegisterMBRPartitions);
KEXPORT(BlockMakeName);
KEXPORT(BlockMakePartName);
